variables:
  SOLUTION: "csharp-metar-decoder"
  VERSION: "1.0"
  LONGVERSION: "$VERSION.$CI_PIPELINE_ID"
  BRANCH: $CI_BUILD_REF_NAME
  PACKAGEID: "csharp-metar-decoder"
  
before_script:
  - 'call D:\Tools\export.v1.bat'
  - echo "starting build for %SOLUTION%"
  - echo "Restoring NuGet Packages..."
  - '"%NUGET%" config -set HTTP_PROXY=%PROXY%'
  - '"%NUGET%" restore %SOLUTION%.sln -configfile .gitlab-ci.NuGet.Config'
  - del /F /Q %CD%\.sonarqube
  - set BUILDMODE=Debug
  - if "%CI_BUILD_REF_NAME%" == "master" set BUILDMODE=Release
  
stages:
  - build
  - test
  - test_sonar

build:
  stage: build
  script:
  - '"D:\\Program Files\\Git\\bin\\git.exe" clean -f'
  - echo "Starting build..."
  - '"%MSBUILD14%" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Debug /nr:False /verbosity:quiet "%SOLUTION%.sln"'

test:
  stage: test
  script:
  - echo "Starting tests"
  - '"%MSBUILD14%" /t:Rebuild "%SOLUTION%.sln"'
  - '%NUNIT%  /result=%CD%\NUnitResults.xml;format=nunit2 %SOLUTION%.sln'
  dependencies:
  - build
  except:
  - develop

test_sonar:
  stage: test_sonar
  script:
  - echo "Starting tests"
  - '%SONAR%  begin /k:"%SOLUTION%" /n:"%SOLUTION%" /v:"%LONGVERSION%" /d:sonar.cs.nunit.reportsPaths="%CD%\NUnitResults.xml" /d:sonar.cs.opencover.reportsPaths=%CD%\opencover.xml'
  - '"%MSBUILD14%" /t:Rebuild "%SOLUTION%.sln"' 
  - '%OPENCOVER% -returntargetcode:10000 -log:All -output:"%CD%\opencover.xml" -register:Path32 -target:"%NUNIT%" -targetargs:" /result=%CD%\NUnitResults.xml;format=nunit2 %SOLUTION%.sln"'
  - '%SONAR%  end'
  dependencies:
  - build
  only:
  - develop