configuration: Release

before_build:
  - nuget restore
  - nuget install NUnit.Runners -Version 3.8.0
  - nuget install OpenCover -Version 4.6.519
  - nuget install coveralls.net -Version 0.412

build:
  project: csharp-metar-decoder.sln
  verbosity: minimal

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: L4yjC/ST1vT5qUl7/LnE57sZRYp9+yc68lL9GjYuPUC35peUxK3PHo9E+TyzBTNF

after_test:
  - dir /s
#  - OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"csharp-metar-decoder-tests.dll" -filter:"+[*]* -[*.Tests]*" -register:user
  - coveralls.net.0.412\tools\Coveralls.exe --opencover -i .\TestResult.xml
