configuration: Release

before_build:
  - nuget restore

build:
  project: csharp-metar-decoder.sln
  verbosity: minimal

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: L4yjC/ST1vT5qUl7/LnE57sZRYp9+yc68lL9GjYuPUC35peUxK3PHo9E+TyzBTNF
