configuration: Release

before_build:
  - nuget restore
  - nuget install NUnit.Runners
  - nuget install OpenCover
  - nuget install coveralls.net

build:
  project: csharp-metar-decoder.sln
  verbosity: minimal

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: L4yjC/ST1vT5qUl7/LnE57sZRYp9+yc68lL9GjYuPUC35peUxK3PHo9E+TyzBTNF

after_test:
  - OpenCover.Console.exe -target:Unit.Runners.nunit-console.exe -targetargs:"/nologo /noshadow csharp-metar-decoder-tests.dll" -filter:"+[*]* -[*.Tests]*" -register:user
  - coveralls.net.Coveralls.exe --opencover -i .results.xml
